### ISSUE TITLE
About routing loss

### ISSUE THREAD

**Issue by abababa-ai** [frank-xwang/RIDE-LongTailRecognition#17]
From the results in Table 4 of the original paper, it seems that the effect of routing loss is not very significant when the number of experts is 2, and even the performance decreases, so what is the benefit of adding routing loss?

**Comment by TonyLianLong** [comment]
Hi @abababa-ai , we add routing loss since it leads to much lower computation with minimal reduction in accuracy. If you remove the routing loss, computation will be way higher and the comparison with baseline will be unfair (if you use more compute, you expect to get a higher accuracy). With routing loss, the FLops roughly match the baseline, and comparison is fair in this way.
