### ISSUE TITLE
How to implement cRT and τ-norm with this framework?

### ISSUE THREAD

**Issue by liming-ai** [frank-xwang/RIDE-LongTailRecognition#19]
Hi, @TonyLianLong :

Thanks for your contribution, is there any instruction for the implementations of cRT and τ-norm? or could you please kindly provide the hyperparameters of cRT and τ-norm  used in in your paper?

**Comment by TonyLianLong** [comment]
You can implement cRT by setting requires_grad to False in backbone and set resample in dataloader to True and then load a trained model without loading linear layer. You can implement tau-norm by modifying the linear layer (using `torch.load` and then modify linear layer, and write the modified layer back to a model).

We follow the hyperparameters in the original decouple paper (see the table in appendix for obtaining hyperparameters). It's a year ago since they are implemented and I don't think I saved the hyperparameters for CIFAR, but I believe if you follow their guide in selection and implementation you can reproduce our cRT and tau-norm. Since I don't think they are sensitive for hyperparameters, the difference will be small. See this file for obtaining the hyperparameters: https://github.com/facebookresearch/classifier-balancing/blob/master/tau_norm.py

**Comment by liming-ai** [comment]
> You can implement cRT by setting requires_grad to False in backbone and set resample in dataloader to True and then load a trained model without loading linear layer. You can implement tau-norm by modifying the linear layer (using `torch.load` and then modify linear layer, and write the modified layer back to a model).
> 
> We follow the hyperparameters in the original decouple paper (see the table in appendix for obtaining hyperparameters). It's a year ago since they are implemented and I don't think I saved the hyperparameters for CIFAR, but I believe if you follow their guide in selection and implementation you can reproduce our cRT and tau-norm. Since I don't think they are sensitive for hyperparameters, the difference will be small. See this file for obtaining the hyperparameters: https://github.com/facebookresearch/classifier-balancing/blob/master/tau_norm.py

Thanks a lot!
