### ISSUE TITLE
The mismatch between code and paper

### ISSUE THREAD

**Issue by sf91971684** [frank-xwang/RIDE-LongTailRecognition#2]
Hello,
Thanks for your great work! I noticed a bug that your paper maximizes the diversity loss while your code minimizes the diversity loss?  Or is there something that misunderstands me？I am looking forward to your reply!
Best Regards,
Feng

**Comment by frank-xwang** [comment]
Hi Feng, thank you for your notice! We did all experiments on the paper with our old codebase, we mistakenly used the wrong symbol when we were cleaning, organizing, and releasing our current codebase. Thanks for catching this issue. After inspecting the code, we found that we moved the minus sign into the factor when re-implementing but did not commit the change in the hyperparameters. Fortunately, this only occurs in the version pushed to GitHub. There is no change to reported experiment results since they are run either with the old codebase or with our local version of the current implementation that has a correct loss. Thank you for letting us know!

Updates: We also conduct the "RIDE (3 experts)" experiment on CIFAR100-LT with the updated codebase. The top 1 acc is 48.7%, which is even 0.7% higher than the 48.0% reported in the paper.
