### ISSUE TITLE
Question about Diversity loss

### ISSUE THREAD

**Issue by singing4you** [frank-xwang/RIDE-LongTailRecognition#31]
Thanks for your great work! But I am confused about the reason why diversity loss works . The paper says that it's a regularization term to encourage complementary decisions.  Why we need complementary decisions from experts?  Don't  we want the same correct answer?  If the experts'  decision is diverse , how can we assure  the final output is correct?

**Comment by TonyLianLong** [comment]
Our architecture is based on the notion of multi-expert models, which is based on bias-variance tradeoff. The reason for introducing multiple experts is to reduce variance. The best way for variance reduction using multi-experts is to have completely independent multi-expert models trained on independently sampled p(x) (data distribution). However, this is not feasible in the real world, since we have only one dataset.

In our setting, we leverage two differences between experts to maintain a lower correlation: one is the randomness in training and parameter initialization and the other is the diversity regularization. Without both techniques, each expert will be the same (because back-propagation does not distinguish the experts), and every expert will give the same output.

As a thought experiment, in your case, if every expert has the same prediction, the will be no variance reduction and we do not even need more than one expert, as the aggregated experts have the same prediction as each of them.

**Comment by singing4you** [comment]
> as the aggregated experts have the same prediction as each of them.

Thanks for your explanation!
