### ISSUE TITLE
the position of  experts

### ISSUE THREAD

**Issue by valencebond** [frank-xwang/RIDE-LongTailRecognition#9]
Thanks for your great code! According to your paper, the experts are located in layer3 and layer4 of resnet.  Do you conduct some ablation study of the position of the experts, such as experts only in layer4 or in layer2, layer3, and layer4?

**Comment by frank-xwang** [comment]
Hi, thanks for your interest in our work and good question! Although deploying experts on layer2 or layer3 has similar parameters as those deployed on layer4, this will significantly increase the overall model flops. To make a fairer comparison with the previous baseline, we hope to ensure that RIDE's flops are basically comparable with the baseline. Because of this, we didn't try to deploy experts in earlier layers. 

If you have any other questions, please let me know.
